"""
Django settings for orchard project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.getenv("SECRET_KEY", None)

if SECRET_KEY is None:
    raise ValueError("SECRET_KEY environment variable is not set")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_ORIGINS = os.getenv("ALLOWED_ORIGINS", "").split(",")

ALLOWED_HOSTS = ["localhost", "127.0.0.1", *ALLOWED_ORIGINS]

# supabase setup
SUPABASE_URL = os.getenv("SUPABASE_URL", None)
SUPABASE_SECRET_KEY = os.getenv("SUPABASE_SECRET_KEY", None)
SUPABASE_JWT_KEY = os.getenv("SUPABASE_JWT_KEY", None)

if SUPABASE_URL is None:
    raise ValueError("SUPABASE_URL environment variable is not set")

if SUPABASE_SECRET_KEY is None:
    raise ValueError("SUPABASE_SECRET_KEY environment variable is not set")

# if SUPABASE_JWT_KEY is None:
#     raise ValueError("SUPABASE_JWT_KEY environment variable is not set")

# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "corsheaders",
    "channels",
    "core",
    "users",
    "bunch",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "orchard.middleware.SupabaseAuthMiddleware",
    "orchard.middleware.SupabaseSessionMiddleware",
]

ROOT_URLCONF = "orchard.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "orchard.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "OPTIONS": {
            "sslmode": "require",
            "pool": True,
        },
    }
}

if "test" in sys.argv:
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": "mydatabase",
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-IN"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model

AUTH_USER_MODEL = "users.User"

# Disable django's built in auth
AUTHENTICATION_BACKENDS = [
    "orchard.authentication.SupabaseAuth",
    "django.contrib.auth.backends.ModelBackend",
]

# DRF

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "orchard.authentication.SupabaseJWTAuthentication",
        # "rest_framework.authentication.BasicAuthentication",
        # "rest_framework.authentication.SessionAuthentication",
    ],
}

# CORS settings
# For coors
FRONTEND_URLS = os.getenv(
    "FRONTEND_URLS", "http://localhost:3000,http://127.0.0.1:3000"
).split(",")
CORS_ALLOWED_ORIGINS = FRONTEND_URLS

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CSRF_COOKIE_SECURE = True

# Channels
ASGI_APPLICATION = "orchard.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}

# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "\033[94m{levelname}\033[0m \033[92m{asctime}\033[0m \033[93m{module}\033[0m \033[96m{funcName}\033[0m {pathname}:{lineno} {message}",  # noqa: E501
            "style": "{",
        },
        "colored": {
            "format": "\033[36m{asctime}\033[0m  [\033[35m{name}\033[0m | \033[1m\033[38;5;208m{levelname}\033[0m] \033[96m{funcName}\033[0m - {message}",  # noqa: E501
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "colored",
        },
    },
    "loggers": {
        "bunch": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
        "orchard": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
        "users": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
        "core": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Orchard API",
    "DESCRIPTION": "Docs for the Bunch API, Orchard",
    "VERSION": "0.0.1",
    "SCHEMA_PATH_PREFIX": "/api/v[0-9]",
}
