# Generated by Django 6.0 on 2025-12-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                blank=True, help_text="User's display name", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="onboarded",
            field=models.BooleanField(
                default=False, help_text="User's onboarding status"
            ),
        ),
    ]
