# Generated by Django 5.1.7 on 2025-05-03 08:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bunch", "0002_alter_member_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bunch",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Bunch",
                "verbose_name_plural": "Bunches",
            },
        ),
        migrations.AlterModelOptions(
            name="channel",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Channel",
                "verbose_name_plural": "Channels",
            },
        ),
        migrations.AlterModelOptions(
            name="member",
            options={
                "ordering": ["-joined_at"],
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("edit_count", models.PositiveIntegerField(default=0)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="bunch.member",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="bunch.channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["created_at"],
            },
        ),
    ]
