# Generated by Django 5.1.7 on 2025-05-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bunch", "0003_alter_bunch_options_alter_channel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bunch",
            name="primary_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("#2c3e50", "Midnight"),
                    ("#f39c12", "Sunset"),
                    ("#1a5276", "Ocean"),
                    ("#27ae60", "Forest"),
                    ("#7b241c", "Burgundy"),
                    ("#af7ac5", "Lilac"),
                    ("#48c9b0", "Turquoise"),
                    ("#707b7c", "Graphite"),
                    ("#f5cba7", "Peach"),
                    ("#1f618d", "Navy"),
                    ("#7d8c42", "Olive"),
                    ("#800000", "Maroon"),
                    ("#00ffff", "Aqua"),
                    ("#da70d6", "Orchid"),
                    ("#333333", "Charcoal"),
                    ("#fa8072", "Salmon"),
                ],
                help_text="Bunch's Primary color",
                max_length=7,
            ),
        ),
    ]
