# Generated by Django 5.1.7 on 2025-05-29 18:14

import bunch.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunch', '0004_bunch_primary_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunch',
            name='primary_color',
            field=models.CharField(choices=[('#2c3e50', 'Midnight'), ('#f39c12', 'Sunset'), ('#1a5276', 'Ocean'), ('#27ae60', 'Forest'), ('#7b241c', 'Burgundy'), ('#af7ac5', 'Lilac'), ('#48c9b0', 'Turquoise'), ('#707b7c', 'Graphite'), ('#f5cba7', 'Peach'), ('#1f618d', 'Navy'), ('#7d8c42', 'Olive'), ('#800000', 'Maroon'), ('#00ffff', 'Aqua'), ('#da70d6', 'Orchid'), ('#333333', 'Charcoal'), ('#fa8072', 'Salmon')], default=bunch.models.get_random_color_choice, help_text="Bunch's Primary color", max_length=7),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(help_text='Emoji character used for reaction', max_length=10, validators=[django.core.validators.RegexValidator(flags=0, message='Must be a valid emoji character', regex='^[\\U0001F600-\\U0001F64F\\U0001F300-\\U0001F5FF\\U0001F680-\\U0001F6FF\\U0001F1E0-\\U0001F1FF\\u2600-\\u26FF\\u2700-\\u27BF]+$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='bunch.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reaction',
                'verbose_name_plural': 'Reactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['message', 'emoji'], name='bunch_react_message_3308bb_idx'), models.Index(fields=['user'], name='bunch_react_user_id_e889d2_idx')],
                'unique_together': {('message', 'user', 'emoji')},
            },
        ),
    ]
