# Generated by Django 5.1.7 on 2025-05-31 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunch', '0005_alter_bunch_primary_color_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='Message this is a reply to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='bunch.message'),
        ),
    ]
