# Generated by Django 5.2.3 on 2025-07-21 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bunch", "0006_message_reply_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="emoji",
            field=models.CharField(
                help_text="Emoji character used for reaction",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        flags=None,
                        message="Must be a valid emoji character",
                        regex="^[\\U0001F600-\\U0001F64F\\U0001F300-\\U0001F5FF\\U0001F680-\\U0001F6FF\\U0001F1E0-\\U0001F1FF\\u2600-\\u26FF\\u2700-\\u27BF]+$",
                    )
                ],
            ),
        ),
    ]
